# Generated by Django 5.1 on 2024-09-10 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Micro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pret',
            name='date_rembourser',
        ),
        migrations.AddField(
            model_name='pret',
            name='etat_pret',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verser',
            name='montant_verser',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rembours', models.DateField()),
                ('montant_rembours', models.FloatField()),
                ('reste_paye', models.FloatField()),
                ('id_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Micro.membre')),
                ('id_pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Micro.pret')),
            ],
        ),
    ]
