# Generated by Django 4.1.7 on 2024-09-09 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Micro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rembourser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rembours', models.DateField()),
                ('montant_rembours', models.FloatField()),
                ('reste_paye', models.FloatField()),
                ('id_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Micro.membre')),
                ('id_pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Micro.pret')),
            ],
        ),
    ]
