# Generated by Django 4.1.7 on 2024-09-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Micro', '0002_rembourser'),
        ('Micro', '0002_remove_pret_date_rembourser_pret_etat_pret_and_more'),
    ]

    operations = [
    ]
