# Generated by Django 4.1.7 on 2024-09-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Micro', '0003_merge_20240923_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deb', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
    ]
