# Generated by Django 4.1.7 on 2024-09-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Micro', '0004_semaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='tampon',
            name='semaine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Micro.semaine'),
        ),
    ]
