# Generated by Django 4.1.7 on 2024-09-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Micro', '0005_tampon_semaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tampon',
            name='date_deb',
        ),
        migrations.RemoveField(
            model_name='tampon',
            name='date_fin',
        ),
    ]
