# Generated by Django 4.1.7 on 2024-10-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Micro', '0006_remove_tampon_date_deb_remove_tampon_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='montant_paye',
            field=models.FloatField(default=0),
        ),
    ]
